//types of actions
export const SET_CHARACTER = 'SET_CHARACTER';
export const REMOVE_CHARACTER = 'REMOVE_CHARACTER';
export const SEARCH_CHARACTER = 'SEARCH_CHARACTER';
export const ADD_CHARACTER = 'ADD_CHARACTER';
